wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.2
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1748818992.0
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 79
      - 80
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 79
      - 80
      3:
      - 23
      4: 3.7.2
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
